server:
  port: 812
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://zxr1998.com.cn/cobweb?characterEncoding=UTF-8&useSSL=false
    username: XRom
    password: XRom45
  session:
    store-type: redis
  redis:
    host: zxr1998.com.cn
    password: XRom19980126.
    database: 1
  resources:
    add-mappings: false
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.cobweb.security.demo.eneity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/mybatis-config.xml
cobweb:
  security:
    browser:
      loginPage: /home/login
      remember-me-seconds: 600
      login-type: json
    code:
      image:
        width: 60
        height: 20
      sms:
        urls: /security/pay/*
    social:
      qq:
        app-id: 101494188
        app-secret: 7aa30095e9f40f66e06d8c1127a6b270
    session:
      max-sessions-prevents-login: true
